# version: "3.9"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      # - "443:443"
      - "8888:8888"
    # volumes:
    #   - html_data:/var/www/html
    # networks:
    #   - frontend
    restart: unless-stopped


# networks:
#   frontend:
#   backend: